(()=>{
 const lang=window.BK_LANG||'ru';
 const labels={ru:{add:'＋ Добавить рецепт',forum:'Форум',rtitle:'Добавить рецепт',author:'Ваше имя',title:'Название рецепта',desc:'Короткое описание',cat:'Категория',ing:'Ингредиенты — каждый с новой строки',steps:'Приготовление — шаги с новой строки',send:'Отправить на модерацию',ok:'Спасибо! Рецепт отправлен на модерацию.',ftitle:'Форум',topic:'Тема',msg:'Сообщение',publish:'Опубликовать',empty:'Пока сообщений нет.'},en:{add:'＋ Add recipe',forum:'Forum',rtitle:'Add a recipe',author:'Your name',title:'Recipe title',desc:'Short description',cat:'Category',ing:'Ingredients — one per line',steps:'Method — one step per line',send:'Send for moderation',ok:'Thank you! Recipe sent for moderation.',ftitle:'Forum',topic:'Topic',msg:'Message',publish:'Publish',empty:'No posts yet.'}};
 const t=labels[lang]||labels.en;
 const tools=document.querySelector('.top .tools'); if(!tools)return;
 const box=document.createElement('div');box.className='communityLinks';box.innerHTML=`<button class="communityBtn primary" id="bkAddRecipe">${t.add}</button><button class="communityBtn" id="bkForum">${t.forum}</button>`;tools.appendChild(box);
 document.body.insertAdjacentHTML('beforeend',`<dialog id="bkRecipeDialog" class="communityPanel"><div class="communityInner"><button class="communityClose" data-c="bkRecipeDialog">×</button><h2>${t.rtitle}</h2><form id="bkRecipeForm" class="communityForm"><input name="author" placeholder="${t.author}"><input name="title" required placeholder="${t.title}"><input name="category" placeholder="${t.cat}"><textarea name="description" required placeholder="${t.desc}"></textarea><textarea name="ingredients" required placeholder="${t.ing}"></textarea><textarea name="steps" required placeholder="${t.steps}"></textarea><button class="communityBtn primary">${t.send}</button><div id="bkRecipeStatus" class="communityNote"></div></form></div></dialog><dialog id="bkForumDialog" class="communityPanel"><div class="communityInner"><button class="communityClose" data-c="bkForumDialog">×</button><h2>${t.ftitle}</h2><form id="bkForumForm" class="communityForm"><input name="name" placeholder="${t.author}"><input name="title" required placeholder="${t.topic}"><textarea name="body" required placeholder="${t.msg}"></textarea><button class="communityBtn primary">${t.publish}</button><div id="bkForumStatus" class="communityNote"></div></form><div id="bkForumList" class="forumList"></div></div></dialog>`);
 const recipe=document.querySelector('#bkRecipeDialog'), forum=document.querySelector('#bkForumDialog');
 document.querySelector('#bkAddRecipe').onclick=()=>recipe.showModal(); document.querySelector('#bkForum').onclick=()=>{forum.showModal();loadForum()};document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>document.querySelector('#'+b.dataset.c).close());
 document.querySelector('#bkRecipeForm').onsubmit=async e=>{e.preventDefault();const st=document.querySelector('#bkRecipeStatus');st.textContent='…';try{const data=Object.fromEntries(new FormData(e.target));const r=await fetch('/api/recipes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw 0;st.textContent=t.ok;e.target.reset()}catch{st.textContent='Ошибка отправки. Проверьте подключение базы D1.'}};
 async function loadForum(){const list=document.querySelector('#bkForumList');list.textContent='…';try{const j=await fetch('/api/forum').then(r=>r.json());list.innerHTML=(j.posts||[]).map(p=>`<article class="forumPost"><h3>${esc(p.title)}</h3><p>${esc(p.body)}</p><small>${esc(p.name)} · ${esc(p.created_at)}</small></article>`).join('')||`<p>${t.empty}</p>`}catch{list.textContent='Ошибка загрузки форума.'}}
 document.querySelector('#bkForumForm').onsubmit=async e=>{e.preventDefault();const st=document.querySelector('#bkForumStatus');st.textContent='…';try{const data=Object.fromEntries(new FormData(e.target));const r=await fetch('/api/forum',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw 0;e.target.reset();st.textContent='OK';await loadForum()}catch{st.textContent='Ошибка отправки.'}};
 function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
})();
